import type { Metadata } from "next";
import { Inter, Onest } from 'next/font/google';
import './globals.css';
import Layout from '../components/layout';
import { Providers } from './providers';

const font = Onest({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Yusrilsptr',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} bg-white dark:bg-black`}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
